# Generated by Django 3.2.3 on 2021-10-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonemod', models.CharField(max_length=20)),
                ('brnd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brands', to='mob.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='Info1',
        ),
    ]
