# Generated by Django 3.2.3 on 2021-10-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob', '0002_auto_20211016_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='mobiles',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ram', to='mob.ram'),
        ),
    ]
