# Generated by Django 3.2.3 on 2021-10-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob', '0003_auto_20211017_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mobiles',
            name='memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Memory', to='mob.memory'),
        ),
    ]
