# Generated by Django 3.2.3 on 2021-12-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob', '0004_auto_20211020_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricecat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricecat', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='mobiles',
            name='pricecat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcat', to='mob.pricecat'),
        ),
    ]
