# Generated by Django 3.2.3 on 2021-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob', '0005_auto_20211227_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
