# Generated by Django 3.2.3 on 2021-12-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob', '0006_mobiles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
